cms/urls.py
from django.conf.urls import url
from cms import views
from django.contrib.auth import views as auth_views

urlpatterns = [
    # 書籍
    url(r'^book/$', views.book_list, name='book_list'),   # 一覧
    url(r'^book/add/$', views.book_edit, name='book_add'),  # 登録
    url(r'^book/mod/(?P<book_id>\d+)/$', views.book_edit, name='book_mod'),  # 修正
    url(r'^book/del/(?P<book_id>\d+)/$', views.book_del, name='book_del'),   # 削除

    # 感想
    url(r'^impression/(?P<book_id>\d+)/$', views.ImpressionList.as_view(), name='impression_list'),  # 一覧
    url(r'^impression/add/(?P<book_id>\d+)/$', views.impression_edit, name='impression_add'),        # 登録
    url(r'^impression/mod/(?P<book_id>\d+)/(?P<impression_id>\d+)/$', views.impression_edit, name='impression_mod'),  # 修正
    url(r'^impression/del/(?P<book_id>\d+)/(?P<impression_id>\d+)/$', views.impression_del, name='impression_del'),   # 削除

    # ログイン
    url(r'^login/$', auth_views.login, name='login'),


    url(r'^logout-then-login/$',
        auth_views.logout_then_login,
        {
            # 今回はsettings.pyで`LOGIN_URL`を指定したので、ここはコメントアウト
            # 'login_url': reverse_lazy('my:login'),
        },
        name='logout_then_login'
    ),


    # ホワイトボード
    url(r'^whiteborde/$', views.whiteborde_list, name='whiteborde_list'),  # 一覧
    # url(r'^whiteborde/add/$', views.whiteborde_edit, name='whiteborde_add'),  # 登録
    #url(r'^whiteborde/mod/(?P<shain_id>\d+)/$', views.whiteborde_edit, name='whiteborde_mod'),  # 修正

    url(r'^whiteborde/whiteborde_status_save/$', views.whiteborde_status_save, name='whiteborde_status_save'),  # 出退勤の更新
    url(r'^whiteborde/whiteborde_work_save/$', views.whiteborde_work_save, name='whiteborde_work_save'),      # 作業場所の更新
    url(r'^whiteborde/whiteborde_biko_save/$', views.whiteborde_biko_save, name='whiteborde_biko_save'),      # 備考の更新
    # url(r'^whiteborde/whiteborde_status_save/(?P<shain_id>\d+)/(?P<status>\d+)/$', views.whiteborde_status_save, name='whiteborde_status_save'),  # 出勤状況更新

]

untitled/urls.py
from django.conf.urls import url, include   # ←, includeを追加
from django.contrib import admin

from django.conf import settings
from django.views.static import serve

from cms.views import whiteborde_list

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^cms/', include('cms.urls', namespace='cms')),  # ←ここを追加
    url(r'^static/(?P<path>.*)$', serve, {'document_root': settings.STATIC_ROOT}),
    url(r'^$', whiteborde_list, name="whiteborde_list"),
]

cms/models.py
from django.db import models
import datetime
from django.contrib.auth.models import User

# Create your models here.


class Book(models.Model):
    """書籍"""
    name = models.CharField('書籍名', max_length=255)
    publisher = models.CharField('出版社', max_length=255, blank=True)
    page = models.IntegerField('ページ数', blank=True, default=0)

    def __str__(self):
        return self.name


class Impression(models.Model):
    """感想"""
    book = models.ForeignKey(Book, verbose_name='書籍', related_name='impressions')
    comment = models.TextField('コメント', blank=True)

    def __str__(self):
        return self.comment


class WhiteBorde(models.Model):
    """ホワイトボード"""
    now = datetime.datetime.now()

    # shain_id = models.CharField('社員ID', max_length=255, primary_key=True)
    staff = models.OneToOneField('Staff', verbose_name='社員番号', related_name='whitebord')
    status = models.CharField('出退勤状況', max_length=10)
    work = models.ForeignKey('Place', verbose_name='作業場所', related_name='whitebord', blank=True, null=True)
    biko = models.CharField('備考', max_length=255, blank=True)
    updatedate = models.DateTimeField('最終更新日', auto_now=True, blank=True, null=True)

    def __str__(self):
        return self.staff.name


class Staff(models.Model):
    """社員"""

    user = models.OneToOneField(User, verbose_name='ユーザ', related_name='staff')
    name = models.CharField('ユーザ名', max_length=255)
    section = models.ForeignKey('Section', verbose_name='セクション', related_name='staff', blank=True, null=True)
    position = models.ForeignKey('Position', verbose_name='ポジション', related_name='staff', blank=True, null=True)

    def __str__(self):
        return self.user.username


class Section(models.Model):
    """セクションマスタ"""

    section = models.CharField('セクション', max_length=255)
    is_edit = models.BooleanField('修正可能フラグ')

    def __str__(self):
        return self.section


class Position(models.Model):
    """ポジションマスタ"""

    position = models.CharField('ポジション', max_length=255)
    is_edit = models.BooleanField('修正可能フラグ')

    def __str__(self):
        return self.position


class Place(models.Model):
    """作業場所マスタ"""

    place = models.CharField('作業場所', max_length=255)

    def __str__(self):
        return self.place

cms/forms.py
from django.forms import ModelForm, DateTimeField
from cms.models import Book, Impression, WhiteBorde


class BookForm(ModelForm):
    """書籍のフォーム"""
    class Meta:
        model = Book
        fields = ('name', 'publisher', 'page', )


class ImpressionForm(ModelForm):
    """感想のフォーム"""
    class Meta:
        model = Impression
        fields = ('comment', )

#
# class WhiteBordeForm(ModelForm):
#     """WhiteBordeのフォーム"""
#
#     updatedate = DateTimeField(input_formats=['%m-%d %H:%M'])
#     #bikoval = 'biko'
#     #biko = bikoval.split("\n").join("<br>");
#
#     class Meta:
#         model = WhiteBorde
#         fields = ('shain_id', 'shain_name', 'status', 'work', 'biko', 'updatedate',)
#         #fields = ('shain_name', 'status', 'biko', )

cms/views.py
import datetime
import requests
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, get_object_or_404, redirect

# Create your views here.
from django.views.decorators.http import require_http_methods

from cms.models import Book, Impression, WhiteBorde, Staff, Place
from cms.forms import BookForm, ImpressionForm
from django.views.generic.list import ListView


@login_required
def book_list(request):
    """書籍の一覧"""
    #    return HttpResponse('書籍の一覧')
    books = Book.objects.all().order_by('id')
    return render(request,
                  'cms/book_list.html',  # 使用するテンプレート
                  {'books': books})  # テンプレートに渡すデータ


def book_edit(request, book_id=None):
    """書籍の編集"""
    #     return HttpResponse('書籍の編集')
    if book_id:  # book_id が指定されている (修正時)
        book = get_object_or_404(Book, pk=book_id)
    else:  # book_id が指定されていない (追加時)
        book = Book()

    if request.method == 'POST':
        form = BookForm(request.POST, instance=book)  # POST された request データからフォームを作成
        if form.is_valid():  # フォームのバリデーション
            book = form.save(commit=False)
            book.save()
            return redirect('cms:book_list')
    else:  # GET の時
        form = BookForm(instance=book)  # book インスタンスからフォームを作成

    return render(request, 'cms/book_edit.html', dict(form=form, book_id=book_id))


def book_del(request, book_id):
    """書籍の削除"""
    #     return HttpResponse('書籍の削除')
    book = get_object_or_404(Book, pk=book_id)
    book.delete()
    return redirect('cms:book_list')


class ImpressionList(ListView):
    """感想の一覧"""
    context_object_name='impressions'
    template_name='cms/impression_list.html'
    paginate_by = 2  # １ページは最大2件ずつでページングする

    def get(self, request, *args, **kwargs):
        book = get_object_or_404(Book, pk=kwargs['book_id'])  # 親の書籍を読む
        impressions = book.impressions.all().order_by('id')   # 書籍の子供の、感想を読む
        self.object_list = impressions

        context = self.get_context_data(object_list=self.object_list, book=book)
        return self.render_to_response(context)


def impression_edit(request, book_id, impression_id=None):
    """感想の編集"""
    book = get_object_or_404(Book, pk=book_id)  # 親の書籍を読む
    if impression_id:   # impression_id が指定されている (修正時)
        impression = get_object_or_404(Impression, pk=impression_id)
    else:               # impression_id が指定されていない (追加時)
        impression = Impression()

    if request.method == 'POST':
        form = ImpressionForm(request.POST, instance=impression)  # POST された request データからフォームを作成
        if form.is_valid():    # フォームのバリデーション
            impression = form.save(commit=False)
            impression.book = book  # この感想の、親の書籍をセット
            impression.save()
            return redirect('cms:impression_list', book_id=book_id)
    else:    # GET の時
        form = ImpressionForm(instance=impression)  # impression インスタンスからフォームを作成

    return render(request,
                  'cms/impression_edit.html',
                  dict(form=form, book_id=book_id, impression_id=impression_id))


def impression_del(request, book_id, impression_id):
    """感想の削除"""
    impression = get_object_or_404(Impression, pk=impression_id)
    impression.delete()
    return redirect('cms:impression_list', book_id=book_id)


@login_required
def whiteborde_list(request):
    """WhiteBordeの一覧"""
    whiteborde = WhiteBorde.objects.all().order_by('staff')

    places = Place.objects.all().order_by('id')

    # jsonで取得
    url = 'https://destination-board.herokuapp.com/api/order/?api_key=a9cdeacb-304e-4182-9559-dfb534604397'
    r = requests.get(url)

    member_data = []
    if r.status_code == 200:
        json = r.json()
        for section in json['data']:
            for member in section['member']:
                member_data.append(
                    {'section_order': section['section_order'],
                     'section_name': section['section_name'],
                     'user_id': member['user_id'],
                     'order': member['order']})

    whiteborde_order = []
    for member_datas in member_data:
        for whiteborde_for in whiteborde:
            if str(whiteborde_for.staff.user) == member_datas['user_id']:
                whiteborde_order.append(whiteborde_for)
                break

    try:
        login_user = Staff.objects.get(user=request.user)
    except Staff.DoesNotExist:
        login_user = None

    if login_user.section.is_edit == True or login_user.position.is_edit:
        is_edit = True
    else:
        is_edit = False

    # # 現在日付
    day = datetime.date.today()

    # # YYYYMMDDで表示
    today = day.strftime("%Y%m%d")
    #
    # whiteborde.kairyo = "3"

    return render(request,
                  'cms/whiteborde_list.html',     # 使用するテンプレート
                  {
                      # 'whitebordes': whiteborde,
                      'whitebordes': whiteborde_order,
                      'nowymd': today,
                      'places': places,
                      'login_user': login_user,
                      'is_edit': is_edit
                  })    # テンプレートに渡すデータ

#
# def whiteborde_edit(request, shain_id=None, shain_name=None):
#     """WhiteBordeの編集"""
#     #     return HttpResponse('書籍の編集')
#     if shain_id:  # shain_id が指定されている (修正時)
#         whiteborde = get_object_or_404(WhiteBorde, pk=shain_id)
#     else:  # shain_id が指定されていない (追加時)
#         whiteborde = WhiteBorde()
#
#     if request.method == 'POST':
#         form = WhiteBordeForm(request.POST, instance=whiteborde)  # POST された request データからフォームを作成
#         if form.is_valid():  # フォームのバリデーション
#             whiteborde = form.save(commit=False)
#             whiteborde.save()
#             return redirect('cms:whiteborde_list')
#     else:  # GET の時
#         form = WhiteBordeForm(instance=whiteborde)  # whiteborde インスタンスからフォームを作成
#
#     return render(request, 'cms/whiteborde_edit.html', dict(form=form, shain_id=shain_id))


#def whiteborde_status_save(request, shain_id=None, status=None):

@require_http_methods(['POST'])
def whiteborde_status_save(request):
    # requestからパラメータを受け取る
    # shain_id = request.GET['shain_id']
    # status = request.GET['status']

    if request.method == 'POST':
        shain_id = request.POST['shain_id']
        status = request.POST['status']

        # 更新するwhitebordeテーブルを絞り込む
        whiteborde = get_object_or_404(WhiteBorde, staff__user__username=shain_id)

        # whitebordeテーブルにパラメータを代入する
        whiteborde.status = status
        # whiteborde.updatedate = datetime.datetime.now()

        # whitebordeテーブルを保存する
        whiteborde.save()

    # ホワイトボード一覧画面の再表示
    return redirect('cms:whiteborde_list')


@require_http_methods(['POST'])
def whiteborde_work_save(request):
    # requestからパラメータを受け取る
    # shain_id = request.GET['shain_id']
    # work = request.GET['work']

    if request.method == 'POST':
        shain_id = request.POST['shain_id']
        # work = request.POST['work']

        work = Place.objects.get(place=request.POST['work'])

        # 更新するwhitebordeテーブルを絞り込む
        whiteborde = get_object_or_404(WhiteBorde, staff__user__username=shain_id)

        # whitebordeテーブルにパラメータを代入する
        whiteborde.work = work
        # whiteborde.updatedate = datetime.datetime.now()

        # whitebordeテーブルを保存する
        whiteborde.save()

    # ホワイトボード一覧画面の再表示
    return redirect('cms:whiteborde_list')


@require_http_methods(['POST'])
def whiteborde_biko_save(request):
    # requestからパラメータを受け取る
    # shain_id = request.GET['shain_id']
    # biko = request.GET['biko']

    if request.method == 'POST':
        shain_id = request.POST['shain_id']
        biko = request.POST['biko']


        biko = biko.replace('<br>', '\r\n')

        # 更新するwhitebordeテーブルを絞り込む
        whiteborde = get_object_or_404(WhiteBorde, staff__user__username=shain_id)

        # whitebordeテーブルにパラメータを代入する
        whiteborde.biko = biko
        # whiteborde.updatedate = datetime.datetime.now()

        # whitebordeテーブルを保存する
        whiteborde.save()

    # ホワイトボード一覧画面の再表示
    return redirect('cms:whiteborde_list')

cms/templates/cms/book_edit.html
{% extends "base.html" %}
{% load bootstrap %}

{% block title %}書籍の編集{% endblock title %}

{% block content %}
    <h3 class="page-header">書籍の編集</h3>
    {% if book_id %}
    <form action="{% url 'cms:book_mod' book_id=book_id %}" method="post" class="form-horizontal" role="form">
    {% else %}
    <form action="{% url 'cms:book_add' %}" method="post" class="form-horizontal" role="form">
    {% endif %}
      {% csrf_token %}
      {{ form|bootstrap_horizontal }}
      <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
          <button type="submit" class="btn btn-primary">送信</button>
        </div>
      </div>
    </form>
    <a href="{% url 'cms:book_list' %}" class="btn btn-default btn-sm">戻る</a>
{% endblock content %}

cms/templates/cms/book_list.html
{% extends "base.html" %}

{% block title %}書籍の一覧{% endblock title %}

{% block extrahead %}
<style>
table {
  margin-top: 8px;
}
</style>
{% endblock %}

{% block content %}
    <h3 class="page-header">書籍の一覧</h3>
    <a href="{% url 'cms:book_add' %}" class="btn btn-default btn-sm">追加</a>
    <table class="table table-striped table-bordered">
      <thead>
        <tr>
          <th>ID</th>
          <th>書籍名</th>
          <th>出版社</th>
          <th>ページ数</th>
          <th>操作</th>
        </tr>
      </thead>
      <tbody>
        {% for book in books %}
        <tr>
          <td>{{ book.id }}</td>
          <td>{{ book.name }}</td>
          <td>{{ book.publisher }}</td>
          <td>{{ book.page }}</td>
          <td>
            <a href="{% url 'cms:book_mod' book_id=book.id %}" class="btn btn-default btn-sm">修正</a>
            <a href="{% url 'cms:book_del' book_id=book.id %}" class="btn btn-default btn-sm">削除</a>
            <a href="{% url 'cms:impression_list' book_id=book.id %}" class="btn btn-default btn-sm btn-primary">感想の一覧</a>
          </td>
        </tr>
        {% endfor %}
      </tbody>
    </table>
    <a href="{% url 'cms:logout_then_login' %}" class="btn btn-default btn-sm">Log Out</a>
{% endblock content %}

cms/templates/cms/impression_edit.html
{% extends "base.html" %}
{% load bootstrap %}

{% block title %}感想の編集{% endblock title %}

{% block content %}
    <h3 class="page-header">感想の編集</h3>
    {% if impression_id %}
    <form action="{% url 'cms:impression_mod' book_id=book_id impression_id=impression_id %}" method="post" class="form-horizontal" role="form">
    {% else %}
    <form action="{% url 'cms:impression_add' book_id=book_id %}" method="post" class="form-horizontal" role="form">
    {% endif %}
      {% csrf_token %}
      {{ form|bootstrap_horizontal }}
      <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
          <button type="submit" class="btn btn-primary">送信</button>
        </div>
      </div>
    </form>
    <a href="{% url 'cms:impression_list' book_id=book_id %}" class="btn btn-default btn-sm">戻る</a>
{% endblock content %}

cms/templates/cms/impression_list.html
{% extends "base.html" %}

{% block title %}感想の一覧{% endblock title %}

{% block extrahead %}
<script>
$(function() {
  $('.del_confirm').on('click', function () {
     $("#del_pk").text($(this).attr("pk"));
     $('#del_url').attr('href', $(this).attr("url"));
  });
});
</script>
<style>
table {
  margin-top: 8px;
}
</style>
{% endblock %}

{% block content %}
    <h3 class="page-header">感想の一覧 <small>{{ book.name }}</small></h3>
    <a href="{% url 'cms:impression_add' book_id=book.id %}" class="btn btn-default btn-sm">追加</a>
    <table class="table table-striped table-bordered">
      <thead>
        <tr>
          <th>ID</th>
          <th>コメント</th>
          <th>操作</th>
        </tr>
      </thead>
      <tbody>
        {% for impression in impressions %}
        <tr>
          <td>{{ impression.id }}</td>
          <td>{{ impression.comment|linebreaksbr }}</td>
          <td>
            <a href="{% url 'cms:impression_mod' book_id=book.id impression_id=impression.id %}" class="btn btn-default btn-sm">修正</a>
            <button class="btn btn-default btn-sm del_confirm" data-toggle="modal" data-target="#deleteModal" pk="{{ impression.id }}" url="{% url 'cms:impression_del' book_id=book.id impression_id=impression.id %}">削除</button>
          </td>
        </tr>
        {% endfor %}
      </tbody>
    </table>

    {% if is_paginated %}
    <ul class="pagination">
      {% if page_obj.has_previous %}
        <li><a href="?page={{ page_obj.previous_page_number }}">&laquo;</a></li>
      {% else %}
        <li class="disabled"><a href="#">&laquo;</a></li>
      {% endif %}
      {% for linkpage in page_obj.paginator.page_range %}
        {% ifequal linkpage page_obj.number %}
          <li  class="active"><a href="#">{{ linkpage }}</a></li>
        {% else %}
          <li><a href="?page={{ linkpage }}">{{ linkpage }}</a></li>
        {% endifequal %}
      {% endfor %}
      {% if page_obj.has_next %}
        <li><a href="?page={{ page_obj.next_page_number }}">&raquo;</a></li>
      {% else %}
        <li class="disabled"><a href="#">&raquo;</a></li>
      {% endif %}
    </ul>
    {% endif %}

    <div>
      <a href="{% url 'cms:book_list' %}" class="btn btn-default btn-sm">戻る</a>
    </div>

{# 削除を確認するモーダル ダイアログ #}
<div class="modal fade" id="deleteModal" tabindex="-1" role="dialog" aria-labelledby="deleteModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h4 class="modal-title" id="deleteModalLabel">確認</h4>
      </div>
      <div class="modal-body">
        <p>ID: <span id="del_pk"></span> を削除しますか？</p>
      </div>
      <div class="modal-footer">
        <a href="#" class="btn btn-primary" id="del_url">OK</a>
        <button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
      </div>
    </div>
  </div>
</div>
{% endblock content %}

cms/templates/cms/whiteborde_edit.html
{% extends "base.html" %}
{% load bootstrap %}

{% block title %}ホワイトボードの編集{% endblock title %}

{% block content %}
    <h3 class="page-header">ホワイトボードの編集</h3>
    {% if shain_id %}
    <form action="{% url 'cms:whiteborde_mod' shain_id=shain_id %}" method="post" class="form-horizontal" role="form">
    {% else %}
    <form action="{% url 'cms:whiteborde_add' %}" method="post" class="form-horizontal" role="form">
    {% endif %}
      {% csrf_token %}
      {{ form|bootstrap_horizontal }}
      <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
          <button type="submit" class="btn btn-primary">送信</button>
        </div>
      </div>
    </form>
    <a href="{% url 'cms:whiteborde_list' %}" class="btn btn-default btn-sm">戻る</a>
{% endblock content %}

cms/templates/cms/whiteborde_list.html
{% extends "base.html" %}
{% load staticfiles %}

{% block title %}ホワイトボードの一覧{% endblock title %}

{% block extrahead %}
    <link type="text/css" href="{% static 'css/whiteborde.css' %}" rel="stylesheet">
    <script type="text/javascript" src="/static/js/javascript.js"></script>
{% endblock %}

{% block content %}
    <h3>ホワイトボードの一覧</h3>
    <h4 id="view_clock" class="page-header" ></h4>

    <a href="{% url 'cms:logout_then_login' %}" class="btn btn-default btn-sm">Log Out</a>
    <span id="user_name" value="21 False">
        ユーザ：{{ login_user.name }}

    </span>

    <div id="other" style="text-align: right">
        <a href="http://www.jslattendance.com/?user_id={{request.user.username}}" target="_blank">
            <button class="btn btn-primary">勤怠</button>
        </a>
    </div>

    <!--<table id="myTBL" class="table table-bordered">-->
    <table id="myTBL" class="table table-striped">
      <thead>
        <tr>
          <th width="10px">社員ID</th>
          <th width="90px">社員名</th>
          <th width="10px">出退勤</th>
          <th width="10px">作業場所</th>
          <th width="400px">備考</th>
          <th width="70px">最終更新日</th>
          <!--<th>社員ID</th>-->
          <!--<th>社員名</th>-->
          <!--<th>出退勤</th>-->
          <!--<th>作業場所</th>-->
          <!--<th>備考</th>-->
          <!--<th>最終更新日</th>-->
        </tr>
      </thead>

      <tbody>
        {% for whiteborde in whitebordes %}
        <form>
            {% csrf_token %}
            {% if whiteborde.status == "出勤" and nowymd != whiteborde.updatedate|date:"Ymd" %}
               <tr id="tr{{whiteborde.staff}}" class="status_over">
            {% else %}
              {% if whiteborde.status == "出勤" %}
                <tr id="tr{{whiteborde.staff}}" class="status_in">
              {% else %}
                <tr id="tr{{whiteborde.staff}}" class="status_out">
              {% endif %}
            {% endif %}

                        <td class="staff_body" td-label="社員番号">{{ whiteborde.staff.user }}</td>
                        <td class="name_body"  td-label="社員名">{{ whiteborde.staff.name }}</td>
                        <td class="status_body" td-label="出退勤">
                            {% if is_edit or whiteborde.staff.user == login_user.user %}
                                <select id="status{{whiteborde.staff}}" name={{ whiteborde.status}} onchange="sel_status('{{whiteborde.staff}}', '{{login_user.user}}', '{% url 'cms:whiteborde_status_save' %}')" class="bgc_edit_ok status">
                            {% else %}
                                <select id="status{{whiteborde.staff}}" disabled name={{ whiteborde.status}} class="bgc_edit_no status">
                            {% endif %}
                                    <option value="出勤"
                                        {% if whiteborde.status == "出勤" %} selected {% endif %}>出勤</option>
                                    <option value="退勤"
                          　　　　　     {% if whiteborde.status == "退勤" %} selected {% endif %}>退勤</option>
                                    {{ whiteborde.status}}
                                </select>
                        </td>

                        <td class="work_body" td-label="作業場所">
                               {#<button type="button" id="note_save{{ staff.user.username }}" onclick="note_save('{{ login_user.user.username }}', '{{ staff.user.username }}', '{% url "white_board:staff_mod_note" %}')" class="btn btn-info btn-sm edit_btn">保存</button>#}

                           {% if is_edit or whiteborde.staff.user == login_user.user %}
                                <select id="work{{whiteborde.staff}}" name='{{ whiteborde.work.place}}' onchange="sel_work('{{whiteborde.staff}}', '{{login_user.user}}', '{% url 'cms:whiteborde_work_save' %}')" class="bgc_edit_ok work">
                           {% else %}
                                <select id="work{{whiteborde.staff}}" disabled name='{{ whiteborde.work.place}}' class="bgc_edit_no work">
                           {% endif %}
                                    {% for place in places %}
                                        {% if place == whiteborde.work %}
                                             <option value="{{ place }}" selected >{{ place }}</option>
                                        {% else %}
                                            <option value="{{ place }}" >{{ place }}</option>
                                        {% endif %}
                                    {% endfor %}
                                </select>
                        </td>

                        <td class="biko_body" td-label="備考">
                           {% if is_edit or whiteborde.staff.user == login_user.user %}
                                <input style="margin-top: 0pt;" type="button" value="クリア" onclick="btn_clear('{{whiteborde.staff}}', '{{login_user.user}}')" class="btn btn-info btn-sm" >
                                <textarea id="biko{{whiteborde.staff}}" rows="1" onkeyup="biko_edit('{{whiteborde.staff}}')" class="bgc_edit_ok biko_width">{{whiteborde.biko}}</textarea>
                                <!--<input type="button" value="保存"   onclick="btn_save('{{whiteborde.shain_id}}')" class="btn btn-danger btn-sm" >-->
                                <input style="margin-top: 0pt;" type="button" value="保存"   onclick="btn_save('{{whiteborde.staff}}', '{{login_user.user}}', '{% url "cms:whiteborde_biko_save" %}')" class="btn btn-danger btn-sm" >
                            {% else %}
                                <input style="margin-top: 0pt;" disabled type="button" value="クリア" class="btn btn-info btn-sm" >
                                <textarea id="biko{{whiteborde.staff}}" disabled rows="1" class="bgc_edit_no biko_width">{{whiteborde.biko}}</textarea>
                                <!--<ut type="button" value="保存"   onclick="btn_save('{{whiteborde.shain_id}}')" class="btn btn-danger btn-sm" >-->
                                <input style="margin-top: 0pt;" type="button" disabled value="保存" class="btn btn-danger btn-sm" >
                            {% endif %}
                        </td>

                    <td class="updatedate_body" td-label="最終更新日">{{whiteborde.updatedate|date:"m/d H:i"}}</td>
                </tr>
            </form>
        {% endfor %}
      </tbody>
    </table>

    <a id="status_save" href="whiteborde_status_save?">
        <button id="status_save_button" hidden>テスト</button>
    </a>
    <a id="work_save" href="whiteborde_work_save?">
        <button id="work_save_button" hidden>テスト</button>
    </a>
    <a id="biko_save" href="whiteborde_biko_save?">
        <button id="biko_save_button" hidden>テスト</button>
    </a>
    {#<a href="{% url 'cms:logout_then_login' %}" class="btn btn-default btn-sm">Log Out</a>#}

  {% endblock content %}